### ISSUE TITLE
This version of libgit2 was not built with ssh memory credentials.

### ISSUE THREAD

**Issue by paritoshraval100** [mfcollins3/libgit2-ios#2]
**Getting below error**

this version of libgit2 was not built with ssh memory credentials." UserInfo={NSLocalizedDescription=this version of libgit2 was not built with ssh memory credentials., NSLocalizedFailureReason=git_clone failed.}

**Comment by mfcollins3** [comment]
Might be related: https://github.com/libgit2/objective-git/issues/571. Perhaps the info to fix it is somewhere in there.

I'm unlikely to fix this in the short-term as I'm not dealing with any projects that use SSH. If someone would like to look into this and submit a PR, I'll happy accept it.

**Comment by mfcollins3** [comment]
Closing this issue since I am archiving this repository.
